version: "3.7"
services:
    app:
        image: node:12-alpine
        command: sh -c "yarn install && yarn run dev && git clone https://github.com/webglearth/webglearth2.git && npm install --save three && make cesium"
        ports:
            - 8000:3000
        working_dir: /nasa_eoo 
        volumes:
            - ./:/nasa_eoo 
        environment:
            MYSQL_HOST: mysql 
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: eoo

    data:
        image: python:3.8
        tty: true #keeps container running
        command: sh -c "pip install --no-cache-dir -r requirements.txt && tail -F /dev/null" 
        # ports:
        #     - 3000:3000
        working_dir: /nasa_eoo 
        volumes:
            - ./:/nasa_eoo 
        environment:
            MYSQL_HOST: mysql 
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: eoo

    mysql:
        image: mysql:5.7
        volumes:
            - nasa_eoo-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: eoo 

volumes:
    nasa_eoo-mysql-data: